name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install  # Додайте цей рядок

    - name: Run tests
      run: npm test

    - name: Run all tests
      run: npm test

    - name: Run registration tests
      run: npm run test:registration

    - name: Run login tests
      run: npm run test:login

    - name: Run visibility tests
      run: npm run test:visibility

    - name: Run clicks tests
      run: npm run test:clicks

    - name: Run shop tests
      run: npm run test:shop
